model:
  input_len: 66
  strand: "ss"
  task: "regression"
  aggr: None
  rnn_kwargs:
    output_dim: 32
    batch_first: True
  fc_kwargs: 
    hidden_dims: [32]
    dropout_rate: 0.2
    batchnorm: True
    output_dim: 1