[tool.poetry]
name = "EUGENe"
packages = [{ include = "eugene" }]
version = "0.1.0"
description = "A Python toolkit for sequence activity prediction and analysis"
authors = ["Adam Klie <aklie@ucsd.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.12,<3.11"
torch = "^1.11.0"
pytorch-lightning = "1.5.10"
torchvision = "^0.12"
captum = "^0.5.0"
numpy = "^1.21.5"
pandas = "^1.3.4"
matplotlib = "^3.5.2"
seaborn = "^0.11.2"
scikit-learn = "^1.0.2"
umap-learn = "^0.5.3"
ipywidgets = "^7.6.5"
pyranges = "^0.0.117"
vizsequence = "^0.1.1"
yuzu-ism = "^0.0.1"
questionary = "^1.10.0"
wget = "^3.2"
rich = "^12.4.4"
Sphinx = {version = "4.4.0", extras = ["docs"]}
myst-parser = {version = "0.18.0", extras = ["docs"]}
sphinxcontrib-apidoc = {version = "0.3.0", extras = ["docs"]}
sphinx-autobuild = {version = "2021.3.14", extras = ["docs"]}
autopep8 = {version = "1.6.0", extras = ["docs"]}
seqlogo = "^5.29.8"
h5py = "^3.7.0"
torch-tb-profiler = "^0.4.0"
openpyxl = "^3.0.9"
black = {version = "^22.3", extras = ["dev"]}
pre-commit = {version = "^2.20", extras = ["dev"]}
pytest = {version = "^7.1.2", extras = ["dev"]}
codecov = {version = "^2.0.8", extras = ["dev"]}
pyBigWig = {version = "^0.3.18", extras = ["janggu"]}
pybedtools = {version = "^0.9.0", extras = ["janggu"]}
biopython = {version = "1.77", extras = ["janggu"]}
progress = {version = "^1.6", extras = ["janggu"]}

[tool.poetry.extras]
docs = ["Sphinx", "myst-parser", "sphinxcontrib-apidoc", "sphinx-autobuild", "autopep8"]
dev = ["black", "pre-commit", "pytest", "codecov"]
janggu = ["pyBigWig", "pybedtools", "biopython", "progress"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
