[tool.poetry]
name = "eugene-tools"
packages = [{ include = "eugene"}]
version = "0.0.4"
description = "A Python toolkit for predictive analyses of regulatory sequences "
authors = ["Adam Klie <aklie@ucsd.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.12,<3.11"
torch = "^1.11.0"
pytorch-lightning = "1.5.10"
torchvision = "^0.12"
captum = "^0.5.0"
numpy = "^1.21.5"
pandas = "^1.3.4"
matplotlib = "^3.5.2"
seaborn = "^0.11.2"
scikit-learn = "^1.0.2"
umap-learn = "^0.5.3"
ipywidgets = "^7.6.5"
pyranges = "^0.0.117"
vizsequence = "^0.1.1"
yuzu-ism = "^0.0.1"
questionary = "^1.10.0"
wget = "^3.2"
rich = "^12.4.4"
seqlogo = "^5.29.8"
logomaker = "^0.8"
h5py = "^3.7.0"
torch-tb-profiler = "^0.4.0"
openpyxl = "^3.0.9"
xlrd = "^2.0.1"
jsonargparse = {version = "4.12.0", extras = ["signatures"]}
Sphinx = {version = "5.1.1", extras = ["docs"]}
myst-parser = {version = "0.18.0", extras = ["docs"]}
sphinxcontrib-apidoc = {version = "0.3.0", extras = ["docs"]}
sphinx-autobuild = {version = "2021.3.14", extras = ["docs"]}
autopep8 = {version = "1.6.0", extras = ["docs"]}
sphinx-autodoc-typehints = {version = "^1.19.2", extras = ["docs"]}
sphinx-rtd-theme = {version = "^1.0.0", extras = ["docs"]}
sphinx-nbexamples = {version = "^0.4.1", extras = ["docs"]}
sphinx-gallery = {version = "^0.11.1", extras = ["docs"]}
nbsphinx = {version = "^0.8.9", extras = ["docs"]}
pandoc = {version = "^2.2", extras = ["docs"]}
black = {version = "^22.3", extras = ["dev"]}
pre-commit = {version = "^2.20", extras = ["dev"]}
pytest = {version = "^7.1.2", extras = ["dev"]}
codecov = {version = "^2.0.8", extras = ["dev"]}
coverage = {version = "^6.5.0", extras = ["dev"]}
pyBigWig = {version = "^0.3.18", extras = ["janggu"]}
pybedtools = {version = "^0.9.0", extras = ["janggu"]}
progress = {version = "^1.6", extras = ["janggu"]}
keras = {version = "^2.4.3", extras = ["janggu"]}
tensorflow = {version = "^2.4.1", extras = ["janggu"]}
Shapely = {version = "^1.8.1", extras = ["kipoi"]}
kipoi = {version = "^0.8.6", extras = ["kipoi"]}
kipoiseq = {version = "^0.7.1", extras = ["kipoi"]}
pyjaspar = {version= "^2.1.0", extras = ["memesuite"]}
pymemesuite = {version = "^0.1.0a1", extras = ["memesuite"]}
biopython = {version = "1.77", extras = ["memesuite"]}

[tool.poetry.extras]
docs = ["Sphinx", "myst-parser", "sphinxcontrib-apidoc", "sphinx-autobuild", "autopep8", "sphinx-autodoc-typehints", "sphinx-rtd-theme", "sphinx-nbexamples", "sphinx-gallery", "nbsphinx", "pandoc"]
dev = ["black", "pre-commit", "pytest", "codecov", "coverage"]
janggu = ["pyBigWig", "pybedtools", "biopython", "progress", "keras", "tensorflow"]
kipoi = ["Shapely", "kipoi", "kipoiseq"]
memesuite = ["pyjaspar", "pymemesuite", "biopython"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
